### ISSUE TITLE
Missing assets in documentation page

### ISSUE THREAD

**Issue by ladhadha** [thecodingmachine/tdbm#1]
Hello, I just trying to open the [Documentation Page](https://thecodingmachine.github.io/tdbm/), and page loaded like screenshoot below

![missing](https://cloud.githubusercontent.com/assets/11268333/26101636/11572188-3a5c-11e7-93fe-85ed631f70e9.png)

I think there is something wrong during the build process.

**Comment by moufmouf** [comment]
Whoo that was quick!

I'm currently working on setting up the documentation website and right now working on this asset problem.
Hopefully, it will be solved in a hours :)

**Comment by moufmouf** [comment]
... aaaaaand it's fixed!

Thanks for letting me know and do not hesitate to post some feedback if you have comments regarding the documentation. I'm heavily working on it right now and comments are really welcome. :)
