### ISSUE TITLE
Foreign keys with default values are not automatically initialized in constructors

### ISSUE THREAD

**Issue by TheoBiron** [thecodingmachine/tdbm#136]
Database : I have a table agreement and a table agreement_status
In my table agreement, i have a column status_id, referencing to the agreement_status with a default value of 1
In the agreement_status table, the line with id = 1 exists

Issue : in the constructor of the AbstractAgreement, the status is not automatically set, we have to provide it as a parameter. Indeed, the status must be an instance of AgreementStatus, and not simply a value, like 1
So right now, the default value is ignored

Solution : if the foreign key has a default value, the constructor should automatically find the object asscoiated to the default value, and set it in the constructor

**Comment by moufmouf** [comment]
This actually cannot be implemented.

Indeed, when we perform a "new MyBean"  call, the "MyBean" class is strictly separated from TDBMService. It has no access to the DAOs and therefore cannot populate the bean with a reference to the `agreement_status` bean.

Therefore, the current behaviour to ask for a reference and ignore the default value is the correct one.
