### ISSUE TITLE
Idea : in jsonSerialize() when $stopReccursion equals true, include the key of the ignored object

### ISSUE THREAD

**Issue by ThibBal** [thecodingmachine/tdbm#152]
Present : When the jsonSerialize() method is called, is the $stopReccursion equals true, the referenced entities are not serialized in the returned data and no key is included to replace the ignore object.

What I would like : In the same situation, include the value of the foreign key column. 

Ex:
- When $stopReccursion === false : 
`` {id: 123, label: "TheCodingMachine", type: {id: 1, label: "Company"}}``

- When $stopReccursion === true : 
`` {id: 123, label: "TheCodingMachine", typeId: 1}``

**Comment by moufmouf** [comment]
:+1: but we should rather keep the same structure as when $stopReccursion === false :

`{id: 123, label: "TheCodingMachine", type: {id: 1}}`
