### ISSUE TITLE
[Feature Request] support strict types in generated getters and setters

### ISSUE THREAD

**Issue by avierr** [thecodingmachine/tdbm#163]

**Comment by moufmouf** [comment]
Hey @avierr ,

May I ask what version of TDBM you are using? TDBM 5.1 (the latest version) comes with strict typing in getters and setters. Do you have an example of generated code that is has no strict types?

**Comment by moufmouf** [comment]
Closing this as there is no feedback. Do not hesitate to add a comment or re-open an issue with more details.
