### ISSUE TITLE
Manual installation guide issues

### ISSUE THREAD

**Issue by SeinopSys** [thecodingmachine/tdbm#164]
I've recently come across this library and I'd like to make use of it in my project that uses no frameworks, but unfortunately I seem to have hit a roadblock right off the bat.

I'm trying to follow the following installation guide: https://thecodingmachine.github.io/tdbm/doc/manual_install.html

The first thing that was immediately obvious upon opening the doc compared to the other ones is that it does not mention what package to even install from Composer, I had to find this repository and get the package name from the Composer JSON.

Then follows the real kicker, taking the code from that page, my IDE immediately complained that I passed no arguments to `new TheCodingMachine\TDBM\Utils\DefaultNamingStrategy()`. Rightfully so, as running the code without it also throws.

`PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function TheCodingMachine\TDBM\Utils\DefaultNamingStrategy::__construct(), 0 passed in file.php on line 22 and exactly 2 expected in .../vendor/thecodingmachine/tdbm/src/Utils/DefaultNamingStrategy.php:40
`

I found this confusing and I'm not really sure how to move forward.

**Comment by moufmouf** [comment]
Hey @SeinopSys ,

Indeed, you are right, the manual install documentation has not been updated with TDBM 5.1 changes.
Thanks for your feedback, I'll update it in the afternoon.

**Comment by moufmouf** [comment]
Hey @SeinopSys ,

Doc has been updated to match TDBM 5.1 installation.

https://thecodingmachine.github.io/tdbm/doc/manual_install.html

Thanks for reporting the issue. Do not hesitate if you find other issues!
