### ISSUE TITLE
Beans the same as beans in RedBeanPHP?

### ISSUE THREAD

**Issue by alystair** [thecodingmachine/tdbm#167]
We currently use RedBeanPHP, but are looking into alternatives. Are 'beans' in your system the same?

**Comment by moufmouf** [comment]
Yes and no :)

In both RedBeanPHP and TDBM, a bean is an object that represent a row in the database. In that sense, they are similar.

Now, RedBeanPHP and TDBM beans are very different. RedBeanPHP beans are using magic properties (__get, __set...), automagically detecting the properties used and using these properties to generate the data model.

By contrast, TDBM takes the exact opposite strategy. It starts from the datamodel and generates the bean classes. One getter/setter is generated for every column (... when you dive in the details of TDBM, you will realize this is not entirely true, but it's a good approximation to get started). So in TDBM, a bean is an instance of a class (generated from the data model) that represents a database row. It has getters and setters explicitly declared (so you benefit from autocompletion in your IDE)
