### ISSUE TITLE
TDBM causes diff when regenerating DAOs (5.0.16)

### ISSUE THREAD

**Issue by WizMik** [thecodingmachine/tdbm#168]
Hello,

Maybe it's fixed on new version, but when generating DAOs, TDBM causes git to detect a diff even if table the structure didn't change, which makes unwanted changes hard to track !

Thx !

**Comment by moufmouf** [comment]
Hey Mike,

Indeed, this was a hard to track issue in TDBM 5.0. This was solved in 5.1 so you should consider upgrading (see #149)

**Comment by WizMik** [comment]
Thanks ! (sorry for the outdated issue !)
