### ISSUE TITLE
Bug generated function with DateTimeImmutable parameter not formatted to string for query

### ISSUE THREAD

**Issue by TheoBiron** [thecodingmachine/tdbm#189]
When you have an unique index between a column of type datetime and others columns, it creates an auto-generated function, which expects a DateTimeImmutable parameter

Issue : this parameter is not formatted in the filter array => it crashes
Fix : Either format the date with a 'default format' (which one ?), or change the parameter type expected

**Comment by moufmouf** [comment]
See:

![image](https://user-images.githubusercontent.com/1290952/72264172-8bc1b980-361a-11ea-9e1d-7aafae4768ee.png)
