### ISSUE TITLE
Mass update a lot of items

### ISSUE THREAD

**Issue by liteultom** [thecodingmachine/tdbm#194]
Hi,

I am looking for a way to update all of my lines in one specific table (switch a boolean on each line). How can I do that without using a loop in PHP which will result, if I am not mistaken, in one SQL request for each line ?

I'd like to have a way to execute a raw SQL request or any other way of updating all of my items at once. Is this possible ? I can't find anything about this in the documentation.

Thanks

**Comment by moufmouf** [comment]
Hey @liteultom ,

> if I am not mistaken, in one SQL request for each line ?

You are not mistaken, this will indeed result in one SQL UPDATE for each line.

There is no way to do mass update with TDBM. This is actually explicitly out of scope of the library.
TDBM is an ORM, and if you look at the issue from an Object Oriented point of view, what you ask means calling the same "setter" method on a result iterator. But the user could overload the setter (in the PHP code) in weird way, so there is no way to do this mass update by only calling "setters".

For this reason, TDBM does not support bulk updates and is not likely to support them in the future.

Your best change here is to use the DBAL connection and write SQL directly.

Sorry!

**Comment by liteultom** [comment]
No problem, thanks for the answer ! We did end up using the DBAL connection :)
