### ISSUE TITLE
`findFromRawSql` count issue

### ISSUE THREAD

**Issue by homersimpsons** [thecodingmachine/tdbm#199]
### Issue

Given the following data:

| id | name | nullable_col |
|----|---------|------------------|
| 1 | John | NULL |
| 2 | Doe | NULL |

The following statement will return 0 instead of the expected count 2:

```php
$this->findFromRawSql('DISTINCT users.* FROM users')->count(); // ==> 0
```

This is because the generated SQL Count query looks like:

```sql
SELECT COUNT(DISTINCT users.id, users.name, users.nullable_col) AS cnt FROM users;
```

### Fix

TDBM should only includes the primary keys in the distinct statement:

```sql
SELECT COUNT(DISTINCT users.id) AS cnt FROM users;
```

In existing projects there is a third parameter that could be used to fix this too:

```php
$this->findFromRawSql(
    'DISTINCT users.* FROM users',
    [],
    'SELECT COUNT(DISTINCT users.id) FROM users'
)->count(); // ==> 2
```

**Comment by moufmouf** [comment]
This is overall a good idea (because MySQL won't have to do a diff on all columns but only on primary keys so this migth improve perf), but I'm pretty sure this won't solve the issue.

Did you try running manually in MySQL;

```sql
SELECT COUNT(DISTINCT users.id, users.name, users.nullable_col) AS cnt FROM users;
```

vs

```sql
SELECT COUNT(DISTINCT users.id) AS cnt FROM users;
```

Are you really getting different results?
