### ISSUE TITLE
Fatal error while generating entities on php 8.1

### ISSUE THREAD

**Issue by maliouba** [thecodingmachine/tdbm#270]
While generating my entities with tdbm:generate, i have two errors:

The first one is located in this file api/vendor/thecodingmachine/tdbm/src/Utils/PivotTableMethodsDescriptor.php
 `Uncaught Error: Class "Doctrine\Common\Inflector\Inflector" not found`. 

After manually fixing the import, the generation for some reason fails with the following error message
`Uncaught Error: Non-static method Doctrine\Inflector\Inflector::pluralize() cannot be called statically`

**Comment by homersimpsons** [comment]
Should be fixed with #271 (released in tdbm v5.3.3)
