### ISSUE TITLE
Cannot save new Bean with a relationship not on primary key

### ISSUE THREAD

**Issue by Zheness** [thecodingmachine/tdbm#57]
Hello,

I have a table `event` with 2 columns:

- `idevent` the primary key
- `nid` an int column

And my second table `preference` with 2 columns:

- `idpreference` the primary key
- `event_nid` an indexed column with a relationship on `event.nid`

When I try to save a new PreferenceBean, I must pass an EventBean, but on save(), it's `event.idevent` which is took instead of `event.nid` according to the relationship.

Thanks

**Comment by moufmouf** [comment]
Closed by #60
